// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Tests.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "api")]
    public partial class DashboardAPIBDDTestsFeature : object, Xunit.IClassFixture<DashboardAPIBDDTestsFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Xunit.ITestOutputHelper _testOutputHelper;
        
        private static string[] featureTags = new string[] {
                "api"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "BDD/Features", "Dashboard API BDD Tests", "  As a test automation engineer\r\n  I want to manage dashboards via the API\r\n  So " +
                "that I can verify the dashboard functionality end-to-end", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Dashboard.feature"
#line hidden
        
        public DashboardAPIBDDTestsFeature(DashboardAPIBDDTestsFeature.FixtureData fixtureData, Xunit.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
#line 8
 await testRunner.GivenAsync("the dashboard API service is configured with valid authentication", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("BDD/Features/Dashboard.feature.ndjson", 12);
        }
        
        async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="Create a dashboard with different names and descriptions")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dashboard API BDD Tests")]
        [global::Xunit.TraitAttribute("Description", "Create a dashboard with different names and descriptions")]
        [global::Xunit.InlineDataAttribute("Short Dashboard", "Short desc", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("Dashboard #007 v2.0", "Dashboard with numeric identifiers", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("CI/CD Pipeline & Build Status", "Tracks build success/failure and deployment rate", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("Dashboard Unicode — テスト", "Dashboard with Unicode characters in name", "3", new string[0])]
        public async global::System.Threading.Tasks.Task CreateADashboardWithDifferentNamesAndDescriptions(string name, string description, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Name", name);
            argumentsOfScenario.Add("Description", description);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create a dashboard with different names and descriptions", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Dashboards can be created with various input combinations", null, tagsOfRule);
#line 12
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
   await testRunner.GivenAsync(string.Format("I have a create request with name \"{0}\" and description \"{1}\"", name, description), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
   await testRunner.WhenAsync("I submit the create dashboard request", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
   await testRunner.ThenAsync("the response should indicate successful creation", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
   await testRunner.AndAsync(string.Format("the returned dashboard name should be \"{0}\"", name), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
   await testRunner.AndAsync(string.Format("the returned dashboard description should be \"{0}\"", description), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.TheoryAttribute(DisplayName="Update a dashboard name and description")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dashboard API BDD Tests")]
        [global::Xunit.TraitAttribute("Description", "Update a dashboard name and description")]
        [global::Xunit.InlineDataAttribute("BDD Update Test - Basic", "Renamed BDD Dashboard", "Automated BDD test dashboard", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("BDD Update Test - Short", "X", "Y", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("BDD Update Test - Special", "Updated: CI/CD & Monitor (v3.0)", "Special chars & \"quotes\" \'apos\'", "6", new string[0])]
        public async global::System.Threading.Tasks.Task UpdateADashboardNameAndDescription(string initialName, string updatedName, string updatedDescription, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("InitialName", initialName);
            argumentsOfScenario.Add("UpdatedName", updatedName);
            argumentsOfScenario.Add("UpdatedDescription", updatedDescription);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Update a dashboard name and description", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Dashboards can be updated after creation", null, tagsOfRule);
#line 28
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 29
   await testRunner.GivenAsync(string.Format("I have a create request with name \"{0}\" and description \"Initial description\"", initialName), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
   await testRunner.AndAsync("I have created the dashboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
   await testRunner.WhenAsync(string.Format("I update the dashboard with name \"{0}\" and description \"{1}\"", updatedName, updatedDescription), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
   await testRunner.ThenAsync("the dashboard update should succeed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 33
   await testRunner.AndAsync(string.Format("the dashboard name should now be \"{0}\"", updatedName), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
   await testRunner.ButAsync(string.Format("the dashboard name should not be \"{0}\"", initialName), ((string)(null)), ((global::Reqnroll.Table)(null)), "But ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Add multiple widgets to a dashboard using a data table")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dashboard API BDD Tests")]
        [global::Xunit.TraitAttribute("Description", "Add multiple widgets to a dashboard using a data table")]
        public async global::System.Threading.Tasks.Task AddMultipleWidgetsToADashboardUsingADataTable()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add multiple widgets to a dashboard using a data table", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Widgets can be added to dashboards", null, tagsOfRule);
#line 44
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 45
   await testRunner.GivenAsync("I have created a dashboard named \"BDD Widget Table Dashboard\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Type",
                            "Width",
                            "Height",
                            "PositionX",
                            "PositionY"});
                table1.AddRow(new string[] {
                            "Overall Statistics Panel",
                            "overallStatistics",
                            "6",
                            "7",
                            "0",
                            "0"});
                table1.AddRow(new string[] {
                            "Launch Statistics Chart",
                            "chart",
                            "6",
                            "4",
                            "6",
                            "0"});
                table1.AddRow(new string[] {
                            "Failed Tests Table",
                            "table",
                            "12",
                            "6",
                            "0",
                            "7"});
#line 46
   await testRunner.WhenAsync("I add the following widgets to the dashboard:", ((string)(null)), table1, "When ");
#line hidden
#line 51
   await testRunner.ThenAsync("the dashboard should contain 3 widgets", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 52
   await testRunner.AndAsync("each widget should have the correct name and type", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Create and verify dashboards from a list of names")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dashboard API BDD Tests")]
        [global::Xunit.TraitAttribute("Description", "Create and verify dashboards from a list of names")]
        public async global::System.Threading.Tasks.Task CreateAndVerifyDashboardsFromAListOfNames()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create and verify dashboards from a list of names", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Widgets can be added to dashboards", null, tagsOfRule);
#line 54
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Name"});
                table2.AddRow(new string[] {
                            "BDD List Dashboard Alpha"});
                table2.AddRow(new string[] {
                            "BDD List Dashboard Beta"});
                table2.AddRow(new string[] {
                            "BDD List Dashboard Gamma"});
#line 55
   await testRunner.GivenAsync("I want to create dashboards with the following names:", ((string)(null)), table2, "Given ");
#line hidden
#line 60
   await testRunner.WhenAsync("I create each dashboard from the list", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
   await testRunner.ThenAsync("all dashboards from the list should be created successfully", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.FactAttribute(DisplayName="Add a single widget using comma-separated widget names list")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Dashboard API BDD Tests")]
        [global::Xunit.TraitAttribute("Description", "Add a single widget using comma-separated widget names list")]
        public async global::System.Threading.Tasks.Task AddASingleWidgetUsingComma_SeparatedWidgetNamesList()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Add a single widget using comma-separated widget names list", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Widgets can be added to dashboards", null, tagsOfRule);
#line 63
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 64
   await testRunner.GivenAsync("I have created a dashboard named \"BDD Widget List Dashboard\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 65
   await testRunner.WhenAsync("I add widgets with names \"Stats Panel,Trend Chart,Failure Table\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
   await testRunner.ThenAsync("the dashboard should have widgets matching the provided names", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.ValueTask Xunit.IAsyncLifetime.InitializeAsync()
            {
                await DashboardAPIBDDTestsFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.ValueTask System.IAsyncDisposable.DisposeAsync()
            {
                await DashboardAPIBDDTestsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
